import { Inter } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css'
import '@fortawesome/fontawesome-free/css/all.min.css'
import "./globals.css";
import BootstrabClient from "@/BootstrabClient/BootstrabClient";
import Navbar from "./Navbar/Navbar";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Top 20",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        {children}
        <BootstrabClient/>
      </body>
    </html>
  );
}
